/**
 * Example PostGate Plugin using TypeScript
 * 
 * This example demonstrates how to use the @postgate/plugin-sdk
 * for type-safe plugin development.
 */

import type {
  PostGatePlugin,
  PluginContext,
  PluginRequest,
  PluginResponse,
  RequestContext,
} from '@postgate/plugin-sdk';

import {
  definePlugin,
  jsonResponse,
  parseJsonBody,
  getResponseBodyText,
} from '@postgate/plugin-sdk';

// Plugin state
let requestCount = 0;

/**
 * Example plugin that logs requests and can modify responses
 */
const plugin: PostGatePlugin = definePlugin({
  name: 'example-ts',
  version: '1.0.0',
  description: 'Example TypeScript plugin for PostGate',

  async onLoad(ctx: PluginContext): Promise<void> {
    ctx.logger.info('Example TypeScript plugin loaded!');

    // Load saved state from storage
    const savedCount = await ctx.storage.get<number>('requestCount');
    if (savedCount !== null) {
      requestCount = savedCount;
      ctx.logger.info(`Restored request count: ${requestCount}`);
    }

    // Register a UI panel
    ctx.ui.registerPanel({
      id: 'example-ts-panel',
      plugin_id: 'example-ts',
      title: 'Example TS',
      icon: 'Code',
      content: {
        type: 'html',
        html: `
          <div style="padding: 16px; font-family: system-ui, sans-serif;">
            <h2 style="margin: 0 0 16px 0;">Example TypeScript Plugin</h2>
            <p>This plugin demonstrates TypeScript development with the SDK.</p>
            <h3 style="margin-top: 16px;">Features:</h3>
            <ul>
              <li>Type-safe API usage</li>
              <li>Request counting with persistence</li>
              <li>Response modification</li>
            </ul>
          </div>
        `,
      },
    });

    ctx.ui.toast('Example TS plugin ready!', 'success');
  },

  async onUnload(ctx: PluginContext): Promise<void> {
    ctx.logger.info('Example TypeScript plugin unloading...');
    
    // Save state before unloading
    await ctx.storage.set('requestCount', requestCount);
    ctx.logger.info(`Saved request count: ${requestCount}`);
    
    // Unregister panel
    ctx.ui.unregisterPanel('example-ts-panel');
  },

  async handleRequest(
    request: PluginRequest,
    ctx: RequestContext
  ): Promise<PluginResponse | null> {
    requestCount++;
    ctx.logger.debug(`Request #${requestCount}: ${request.method} ${request.path}`);

    // Example: Parse JSON body if present
    if (request.body) {
      const jsonBody = parseJsonBody<Record<string, unknown>>(request);
      if (jsonBody) {
        ctx.logger.debug(`Request body: ${JSON.stringify(jsonBody)}`);
      }
    }

    // Example: Intercept specific path
    if (request.path === '/api/example') {
      return jsonResponse({
        message: 'This response was generated by the example plugin',
        requestCount,
        timestamp: new Date().toISOString(),
      });
    }

    // Pass through to the actual server
    return null;
  },

  async handleResponse(
    request: PluginRequest,
    response: PluginResponse,
    ctx: RequestContext
  ): Promise<PluginResponse> {
    // Example: Add custom header to all responses
    const modifiedHeaders = {
      ...response.headers,
      'x-postgate-plugin': 'example-ts',
      'x-request-count': String(requestCount),
    };

    // Example: Log response body for JSON responses
    if (response.headers['content-type']?.includes('application/json')) {
      const bodyText = getResponseBodyText(response);
      if (bodyText) {
        ctx.logger.debug(`Response body length: ${bodyText.length}`);
      }
    }

    return {
      ...response,
      headers: modifiedHeaders,
    };
  },
});

export default plugin;
